import { SubscriptionType } from "@prisma/client";

export const subscription_plan = [
    {
        id: "5ccee5ef-f993-4e48-bced-dfce30fe65c1",
        name: "Free Bot",
        type: SubscriptionType.FIXED,
        active: true,
        validity_start: new Date(),
        validity_end: new Date(),
        price: 0,
        minimum_months_of_subscription: 30,
        maximum_months_of_advance_payment: 60,
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
        trader_robot_id: "bc313f38-e478-4299-9323-44774495d120",
    },
    {
        id: "85a7cef6-05ea-4e19-858c-fa25b3d5330a",
        name: "Inteligente FX",
        type: SubscriptionType.FIXED,
        active: true,
        validity_start: new Date(),
        validity_end: new Date(),
        price: 39.9,
        minimum_months_of_subscription: 30,
        maximum_months_of_advance_payment: 60,
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
        trader_robot_id: "22f98527-e68e-4703-a241-466270c185f6",
    },
    {
        id: "796770d8-594f-410a-b1e0-e591a0778dee",
        name: "Master Bot",
        type: SubscriptionType.FIXED,
        active: true,
        validity_start: new Date(),
        validity_end: new Date(),
        price: 69.9,
        minimum_months_of_subscription: 30,
        maximum_months_of_advance_payment: 60,
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
        trader_robot_id: "854ea78e-8f41-4b56-aadc-428a7e728312",
    },

    {
        id: "29dc0679-a162-4943-bebb-7e9e7599d3aa",
        name: "Optimus Bot",
        type: SubscriptionType.FIXED,
        active: true,
        validity_start: new Date(),
        validity_end: new Date(),
        price: 49.9,
        minimum_months_of_subscription: 30,
        maximum_months_of_advance_payment: 60,
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
        trader_robot_id: "04f3e545-bcca-462b-bbb9-28a6097ad4ae",
    },
    {
        id: "305a5c21-2ab1-404c-9e81-d5b4cb892c39",
        name: "Smart Bot",
        type: SubscriptionType.FIXED,
        active: true,
        validity_start: new Date(),
        validity_end: new Date(),
        price: 99.9,
        minimum_months_of_subscription: 30,
        maximum_months_of_advance_payment: 60,
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
        trader_robot_id: "26e62734-6698-4d55-b2de-58f67c99152f",
    },
];
