export const trader_robot = [
    {
        id: "bc313f38-e478-4299-9323-44774495d120",
        name: "Free Bot",
        logo_url: "http://",
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
    },
    {
        id: "22f98527-e68e-4703-a241-466270c185f6",
        name: "Inteligente FX",
        logo_url: "http://",
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
    },
    {
        id: "854ea78e-8f41-4b56-aadc-428a7e728312",
        name: "Master Bot",
        logo_url: "http://",
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
    },
    {
        id: "04f3e545-bcca-462b-bbb9-28a6097ad4ae",
        name: "Optimus Bot",
        logo_url: "http://",
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
    },
    {
        id: "26e62734-6698-4d55-b2de-58f67c99152f",
        name: "Smart Bot",
        logo_url: "http://",
        created_at: new Date(),
        created_by: "SEED",
        updated_at: new Date(),
        updated_by: "SEED",
        deleted_at: null,
        deleted_by: null,
    },
];
